[[plugins]]
repo = "sainnhe/gruvbox-material"
hook_add = 'source ~/.config/nvim/plugins/gruvbox.vim'
merged = false
overwrite = true

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --bin'
merged = '0'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
hook_add = '''
  command! -bang -nargs=* Rg
    \ call fzf#vim#grep(
    \   'rg --line-number --no-heading '.shellescape(<q-args>), 0,
    \   fzf#vim#with_preview({'options': '--exact --reverse'}, 'right:50%:wrap'))
'''

# LSPとか
[[plugins]]
repo = 'neoclide/coc.nvim'
rev = "release"
hook_add = 'source ~/.config/nvim/plugins/coc.vim'
merged = false
overwrite = true

# vim上でコンパイル･実行
[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = 'source ~/.config/nvim/plugins/quickrun.vim'
merged = false
overwrite = true

# 非同期
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'
merged = false
overwrite = true

# 非同期でsyntaxチェック
[[plugins]]
repo = 'w0rp/ale'
hook_add = 'source ~/.config/nvim/plugins/ale.vim'
merged = false
overwrite = true

############################
# For Git
############################

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = 'source ~/.config/nvim/plugins/gitgutter.vim'
merged = false
overwrite = true

# vimからgitを呼べる
# :Gstatus
# :Gdiff
# :Gblame
[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = 'source ~/.config/nvim/plugins/fugitive.vim'
merged = false
overwrite = true

# 括弧補完･削除
[[plugins]]
repo = 'jiangmiao/auto-pairs'
merged = false
overwrite = true



#[[plugins]]
#repo = 'Shougo/denite.nvim'
#hook_add = 'source ~/.config/nvim/plugins/denite.vim'


# [[plugins]]
# repo = 'kassio/neoterm'
# hook_add = 'source ~/.config/nvim/plugins/neoterm.vim'
# merged = false
# overwrite = true


# Filer
[[plugins]]
repo = 'lambdalisue/fern.vim'
hook_add = 'source ~/.config/nvim/plugins/fern.vim'
merged = false
overwrite = true

[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'

[[plugins]]
repo = 'lambdalisue/nerdfont.vim'

[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'
hook_add = '''
let g:fern#renderer = 'nerdfont'
'''

[[plugins]]
repo = 'lambdalisue/glyph-palette.vim'
hook_add = 'source ~/.config/nvim/plugins/glyph-palette.vim'


# [[plugins]]
# repo = 'andys8/vim-elm-syntax'
# on_ft = ['elm']
# merged = false
# overwrite = true

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'LnL7/vim-nix'
