[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'tomasr/molokai'


[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'mhartington/oceanic-next'

[[plugins]]
repo = 'joshdick/onedark.vim'

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']

[[plugins]]
repo = 'vim-airline/vim-airline-themes'


[[plugins]]
repo = 'Lokaltog/vim-powerline'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'thinca/vim-quickrun'

#[[plugins]]
#repo = 'ElmCast/elm-vim'

[[plugins]]
repo = 'prabirshrestha/async.vim'

#[[plugins]]
#repo = 'prabirshrestha/vim-lsp'

#[[plugins]]
#repo = 'mattn/vim-lsp-settings'
#
#[[plugins]]
#repo = 'mattn/vim-lsp-icons'
#
#[[plugins]]
#repo = 'mattn/vim-foimports'

#[[plugins]]
#repo = 'prabirshrestha/asyncomplete.vim'
#
#[[plugins]]
#repo = 'prabirshrestha/asyncomplete-lsp.vim'

#[[plugins]]
#repo = 'Shougo/deoplete.nvim'

#[[plugins]]
#repo = 'lighttinger2505/deoplete-vim-lsp'

# [[plugins]]
# repo = 'hrsh7th/vim-vsnip'
# 
# [[plugins]]
# repo = 'hrsh7th/vim-vsnip-integ'

# [[plugins]]
# repo = 'neovim/nvim-lsp'

[[plugins]]
repo = 'neoclide/coc.nvim'
build = './install.sh nightly'
book_add = 'source ~/.config/nvim/coc-settings.json'
