# 見た目
[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = 'source ~/.config/nvim/plugins/airline.vim'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

# LSPとか
[[plugins]]
repo = 'neoclide/coc.nvim'
build = './install.sh nightly'
hook_add = 'source ~/.config/nvim/plugins/coc.vim'

# vim上でコンパイル･実行
[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = 'source ~/.config/nvim/plugins/quickrun.vim'

# 非同期
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

# 非同期でsyntaxチェック
[[plugins]]
repo = 'w0rp/ale'

# gitのdiffを表示したり差分を戻したり
[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = 'source ~/.config/nvim/plugins/gitgutter.vim'


# 括弧補完･削除
[[plugins]]
repo = 'jiangmiao/auto-pairs'

# vimからgitを呼べる
# :Gstatus
# :Gdiff
# :Gblame
[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = 'source ~/.config/nvim/plugins/fugitive.vim'

# vim用の統合インターフェイス
[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = 'source ~/.config/nvim/plugins/denite.vim'
